name: mapie-ci
channels:
    - defaults
    - conda-forge
dependencies:
    - codecov
    - flake8==4.0.1
    - black==22.8.0
    - mypy
    - pytest
    - pytest-cov
    - pytest-mock
    - twine
    - wheel
    - pandas
    - pip:
        - -e .
